### ISSUE TITLE
Generalise to multiple programs

### ISSUE THREAD

**Issue by pmonks** [finos-fdx/contrib-toolbox#3]
Right now the `oc-deploy.sh` is tightly coupled to the Symphony Program's activities (i.e. the ssf-dev and ssf-prod targets).  In the not-too-distant future, it needs to be generalised to support any Program.

**Comment by maoo** [comment]
We haven't heard any request for OpenShift (and Symphony-related) deployments. Closing the issue for now, we'll reopen if anything changes.
