### ISSUE TITLE
Consider using ScanCode to scan incoming contributions

### ISSUE THREAD

**Issue by pombredanne** [finos-fdx/contrib-toolbox#5]
Have you considered using [scancode-toolkit](https://github.com/nexB/scancode-toolkit) to check for incoming contribs licenses? that's something I had discussed briefly with @copiesofcopies last year. I'd be glad to help!

**Comment by maoo** [comment]
Hi @pombredanne , thanks for the feedback, the scancode-toolkit looks promising! Took the freedom to add the comment to https://finosfoundation.atlassian.net/browse/ODP-47 , which is where we're tracking the requirements; I was looking at FOSSA lately, as I am quite pleased how they manage builds across many programming languages and build systems. I'll check which languages scancode-toolkit supports and keep you posted with my investigation. Thank you!
